"$schema" = "https://starship.rs/config-schema.json"
add_newline = true
command_timeout = 500
format = "   $username$os$hostname$localip$shlvel$directory${custom.jj}$git_branch$git_commit$git_state$git_metrics$git_status$docker_context$package$c$cmake$deno$golang$lua$python$rust$nix_shell$conda$aws$gcloud$openstack$azure$fill$cmd_duration$status$time$line_break$container$character"
palette = "catppuccin_mocha"
scan_timeout = 30

[character]
error_symbol = "[󰳠](red)"
success_symbol = "[󰳠](lavender)"

[cmd_duration]
format = "([\\[$duration  \\]]($style) )"

[directory]
read_only = " 🔒"
style = "bold blue"

[fill]
symbol = " "

[custom.jj]
command = "prompt"
format = "$output"
ignore_timeout = true
shell = ["starship-jj", "--ignore-working-copy", "starship"]
use_stdin = false
when = "test \"$PWD\" != \"$HOME/code/tyrex/station-refactor\" && jj root"

[git_branch]
style = "bold purple"

[git_commit]
only_detached = true
style = "bold green"

[git_metrics]
disabled = true
format = "([ $added]($added_style)) ([ $deleted]($deleted_style)) "

[git_state]
cherry_pick = "[ PICKING](bold yellow)"
merge = "[ MERGING](bold yellow)"
rebase = "[ REBASE](bold yellow)"

[git_status]
ahead = "🏎💨"
behind = "😰"
conflicted = "🏳"
deleted = "🗑"
diverged = "😵"
format = "([\\[](bold red)$all_status$ahead_behind[\\]](bold red) )"
modified = "📝"
renamed = "👅"
staged = "[󰓜 \\($count\\)](green)"
stashed = "📦"
untracked = "🤷"
up_to_date = "[✓](green)"

[hostname]
ssh_only = true
style = "green"

[localip]
disabled = true
ssh_only = true
style = "flamingo"

[os]
disabled = false

[package]
disabled = true

[palettes.catppuccin_mocha]
base = "#1e1e2e"
blue = "#89b4fa"
crust = "#11111b"
flamingo = "#f2cdcd"
green = "#a6e3a1"
lavender = "#b4befe"
mantle = "#181825"
maroon = "#eba0ac"
mauve = "#cba6f7"
overlay0 = "#6c7086"
overlay1 = "#7f849c"
overlay2 = "#9399b2"
peach = "#fab387"
pink = "#f5c2e7"
red = "#f38ba8"
rosewater = "#f5e0dc"
sapphire = "#74c7ec"
sky = "#89dceb"
subtext0 = "#a6adc8"
subtext1 = "#bac2de"
surface0 = "#313244"
surface1 = "#45475a"
surface2 = "#585b70"
teal = "#94e2d5"
text = "#cdd6f4"
yellow = "#f9e2af"

[status]
disabled = false
format = " [$symbol$status]($style) "

[time]
disabled = false

[username]
show_always = false
