# Chezmoi configuration for Vincent's dotfiles with 1Password integration
# Save this as ~/.config/chezmoi/chezmoi.toml

[data]
    # User information
    name = "Vincent Berthier"
    email = "vincent.berthier@posteo.org"
    tyrex_name = "Vincent BERTHIER"
    tyrex_mail = "vincent.berthier@tyrex-cyber.com"
    tyrex_code_root = "code/tyrex"
    
    # System information
    hostname = "{{ .chezmoi.hostname }}"
    username = "{{ .chezmoi.username }}"
    
    # Font configuration
    font = "Dank Mono"
    font_mono = "Dank Mono"
    
    # Keyboard layout
    keyboard = "bepo"

[onepassword]
    # Enable 1Password integration
    prompt = true
    
    # 1Password item references for secrets
    # Format: op://vault/item/field

[data.hyprland]
    # Hyprland configuration per hostname
    # This will be templated based on your original config.json structure
    
    [data.hyprland.gaia]
        workspace1 = "name:chat"
        workspace2 = "name:general" 
        workspace3 = "name:dev"
        workspace4 = "name:misc"
        workspace5 = "name:webdev"
        workspace6 = "name:work"
        workspace7 = "name:obsidian"
        workspace8 = "name:gaming"
        workspace9 = "name:spotify"
        workspace10 = "name:astro"
        workspace11 = "name:remote"
        discord = "discord"
        browser = "zen-browser"
        monitors = [
            "DP-1, 1920x1080@144, 0x0, 1",
            "DP-2, 1920x1080@144, 1920x0, 1", 
            "DP-3, 1920x1080@144, 3840x0, 1"
        ]
        monitor1 = "DP-1"
        monitor2 = "DP-2"
        monitor3 = "DP-3"
        env = ["AQ_DRM_DEVICES,/dev/dri/card1"]
        
    [data.hyprland.athena]
        workspace1 = "1"
        workspace2 = "2"
        workspace3 = "3"
        workspace4 = "4" 
        workspace5 = "5"
        workspace6 = "6"
        workspace7 = "7"
        workspace8 = "8"
        workspace9 = "9"
        workspace10 = "10"
        workspace11 = "11"
        discord = "webcord"
        browser = "zen-browser"
        monitors = ["eDP-1, 1920x1080@60, 0x0, 1"]
        monitor1 = "eDP-1"
        monitor2 = "eDP-1" 
        monitor3 = "eDP-1"
        env = [
            "WLR_DRM_DEVICES,/dev/dri/card1:/dev/dri/card0",
            "AQ_DRM_DEVICES,/dev/dri/card1:/dev/dri/card0",
            "LIBVA_DRIVER_NAME,nvidia",
            "XDG_SESSION_TYPE,wayland",
            "GBM_BACKEND,nvidia-drm",
            "__GLX_VENDOR_LIBRARY_NAME,nvidia",
            "WLR_NO_HARDWARE_CURSORS,1"
        ]
        idle_config = { listener = { timeout = 360, on-timeout = "hyprlock" } }
        
    [data.hyprland.hephaistos]
        workspace1 = "name:chat"
        workspace2 = "name:general"
        workspace3 = "name:dev" 
        workspace4 = "name:misc"
        workspace5 = "name:webdev"
        workspace6 = "name:work"
        workspace7 = "name:obsidian"
        workspace8 = "name:gaming"
        workspace9 = "name:spotify"
        workspace10 = "name:astro"
        workspace11 = "name:remote"
        discord = "discord"
        browser = "zen-browser"
        monitors = [
            "DP-1, 1920x1080@60, 0x0, 1",
            "DP-2, 1920x1080@60, 1920x0, 1",
            "DP-3, 1920x1080@60, 3840x0, 1"
        ]
        monitor1 = "DP-1"
        monitor2 = "DP-2"
        monitor3 = "DP-3"
        env = ["AQ_DRM_DEVICES,/dev/dri/card1"]
        idle_config = { listener = { timeout = 360, on-timeout = "hyprlock" } }

[data.waybar]
    # Waybar configuration per hostname
    
    [data.waybar.gaia]
        workspace1 = "chat"
        workspace2 = "general"
        workspace3 = "dev"
        workspace4 = "misc"
        workspace5 = "webdev"
        workspace6 = "work"
        workspace7 = "obsidian"
        workspace8 = "gaming" 
        workspace9 = "spotify"
        workspace10 = "astro"
        workspace11 = "remote"
        wifi = "wlp16s0"
        modules_right = [
            "custom/spotify",
            "pulseaudio",
            "pulseaudio#microphone",
            "custom/updates",
            "cpu",
            "memory",
            "custom/backup",
            "network",
            "custom/vpn",
            "tray",
            "custom/logout"
        ]
        output = ["DP-1", "DP-2", "DP-3"]
        
    [data.waybar.athena]
        battery = "true"
        workspace1 = "1"
        workspace2 = "2"
        workspace3 = "3"
        workspace4 = "4"
        workspace5 = "5"
        workspace6 = "6"
        workspace7 = "7"
        workspace8 = "8"
        workspace9 = "9"
        workspace10 = "10"
        workspace11 = "11"
        wifi = "wlp2s0"
        modules_right = [
            "custom/spotify",
            "pulseaudio", 
            "pulseaudio#microphone",
            "custom/updates",
            "custom/vpn",
            "cpu",
            "memory",
            "battery",
            "custom/backup",
            "network",
            "tray",
            "custom/logout"
        ]
        output = ["eDP-1"]
        
    [data.waybar.hephaistos]
        workspace1 = "chat"
        workspace2 = "general"
        workspace3 = "dev"
        workspace4 = "misc"
        workspace5 = "webdev"
        workspace6 = "work"
        workspace7 = "obsidian"
        workspace8 = "gaming"
        workspace9 = "spotify"
        workspace10 = "astro"
        workspace11 = "remote"
        wifi = "wlp16s0"
        modules_right = [
            "custom/spotify",
            "pulseaudio",
            "pulseaudio#microphone", 
            "custom/updates",
            "custom/vpn",
            "cpu",
            "memory",
            "custom/backup",
            "network",
            "tray",
            "custom/logout"
        ]
        output = ["DP-1", "DP-2", "DP-3"]

[edit]
    # Configure editor for chezmoi edit commands
    command = "helix"

[git]
    # Git configuration for chezmoi
    autoCommit = true
    autoPush = true
    
[diff]
    # Diff configuration
    command = "difft"

[merge]
    # Merge tool configuration 
    command = "meld"

[cd]
    # Change to source directory after chezmoi commands
    command = "{{ .chezmoi.sourceDir }}"

[template]
    # Template options
    options = ["missingkey=error"]
